client/urls.py
from django.urls import path
from . import views

app_name = 'client'

urlpatterns = [
    path('', views.index, name="index"),
    path('index-top-menu/', views.index_top_menu, name="index_top_menu"),
    path('index-video/', views.index_video, name="index_video"),
    path('showcase/', views.showcase, name="showcase"),
    path('wave/', views.wave, name="wave"),
    path('services/', views.services, name="services"),
    path('news/', views.news, name="news"),
    path('news-detail/<int:id>/', views.news_detail, name="news_detail"),
    path('work-detail/', views.work_detail, name="work_detail"),
    path('contact/', views.contact, name="contact"),
    path('career/', views.career, name="career"),
    path('documentation/', views.documentation, name="documentation"),



    # path('report-history/', views.reportHistory, name="reportHistory"),
    # path('finalize-report/', views.finalizeReport, name="finalizeReport"),
    # path('save-report/', views.saveReport, name="saveReport"),
    

    # path('view-report-details/<int:pk>', views.viewReportDetails, name="viewReportDetails"),
    # path('review-image/<int:pk>', views.reviewImage, name="reviewImage"),

    # path('view-profile/', views.viewProfile, name="viewProfile"),
    # path('update-profile/', views.updateProfile, name="updateProfile"),

    # path('logout/', views.user_logout, name='user_logout'),
    # path('reset-password/', views.resetPassword, name="resetPassword"),
    # path('ajax/load-link/', views.load_review, name='ajax_load_review'),

    # path('download-report/<int:pk>', views.downloadReport, name="downloadReport"),

    # path('', views.login, name="login"),
    # path('login/', views.logins, name="logins"),
    # path('index/', views.index, name="index"),
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.login, name="login"),

    path('forgot-password/', views.forgotPassword, name="forgotPassword"),
    path('verify-code/', views.verifyCode, name="verifyCode"),

    path('reset-password/<str:token>', views.resetPassword, name='resetPassword'),

    # path('index/', views.index, name="index"),
]

wavex/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt
from wavex import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superuser/', include('superuser.urls')),
    path('login/', include('login.urls')),
    path('', include('client.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

client/models.py
from django.db import models

# Create your models here.

client/views.py
from django.shortcuts import render
from superuser.models import *
from django.core.mail import send_mail, EmailMessage
from django.conf import settings
import environ
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib import messages
from django.shortcuts import redirect, render
from datetime import datetime

env = environ.Env()
environ.Env.read_env()


# Create your views here.
def index(request):
    template_name = 'client/index.html'
    images = Image.objects.all()
    videos = Video.objects.all()
    banners = Image.objects.filter(banner=True)
    current_year = datetime.now().year

    if videos.count() > 0:
        video = videos.first()
    else:
        video = None  

 

    return render(request, template_name, {
        'images': images,
        'videos': videos,
        'banners': banners,
        'video': video,
        'current_year': current_year
    })

    

def index_top_menu(request):
    template_name = 'client/index-top-menu.html'

    images = Image.objects.all()
    videos = Video.objects.all()
    banners = Image.objects.filter(banner=True)
    current_year = datetime.now().year

    if videos.count() > 0:
        video = videos.first()
    else:
        video = None  

    return render(request, template_name, {
        'images': images,
        'videos': videos,
        'banners': banners,
        'video': video,
        'current_year': current_year
    })


def index_video(request):
    template_name = 'client/index-video.html'

    images = Image.objects.all()
    videos = Video.objects.all()
    banners = Image.objects.filter(banner=True)
    current_year = datetime.now().year

    if videos.count() > 0:
        video = videos.first()
    else:
        video = None  

    return render(request, template_name, {
        'images': images,
        'videos': videos,
        'banners': banners,
        'video': video,
        'current_year': current_year
    })


def showcase(request):
    template_name = 'client/showcase.html'

    images = Image.objects.all()
    videos = Video.objects.all()
    banners = Image.objects.filter(banner=True)
    current_year = datetime.now().year

    if videos.count() > 0:
        video = videos.first()
    else:
        video = None  

    return render(request, template_name, {
        'images': images,
        'videos': videos,
        'banners': banners,
        'video': video,
        'current_year': current_year
    })


def wave(request):
    template_name = 'client/wave.html'

    images = Image.objects.all()
    videos = Video.objects.all()
    banners = Image.objects.filter(banner=True)
    current_year = datetime.now().year

    if videos.count() > 0:
        video = videos.first()
    else:
        video = None    


    return render(request, template_name, {
        'images': images,
        'videos': videos,
        'banners': banners,
        'video': video,
        'current_year': current_year
    })


def services(request):
    template_name = 'client/services.html'

    images = Image.objects.all()
    videos = Video.objects.all()
    banners = Image.objects.filter(banner=True)
    current_year = datetime.now().year

    if videos.count() > 0:
        video = videos.first()
    else:
        video = None  

    return render(request, template_name, {
        'images': images,
        'videos': videos,
        'banners': banners,
        'video': video,
        'current_year': current_year

    })


def news(request):
    template_name = 'client/news.html'

    blogs = Blog.objects.all()
    current_year = datetime.now().year

    return render(request, template_name, {
        'blogs': blogs,
        'current_year': current_year
    })



def news_detail(request, id, *args, **kwargs):
    template_name = 'client/news-detail.html'
    page = "View Blog"

    blog = Blog.objects.get(id=id)
    current_year = datetime.now().year

    return render(request, template_name, {
        'page': page,
        'blog': blog,
        'current_year': current_year
    }) 



def work_detail(request):
    template_name = 'client/work-detail.html'

    images = Image.objects.all()
    videos = Video.objects.all()
    banners = Image.objects.filter(banner=True)
    current_year = datetime.now().year

    if videos.count() > 0:
        video = videos.first()
    else:
        video = None  

    return render(request, template_name, {
        'images': images,
        'videos': videos,
        'banners': banners,
        'video': video,
        'current_year': current_year
    })


def contact(request):
    template_name = 'client/contact.html'
    current_year = datetime.now().year



    if request.method == 'POST':

        user_name = request.POST.get('name')
        user_email = request.POST.get('email')
        user_subject = request.POST.get('subject')
        user_message = request.POST.get('message')

        # Function to send mail to admin
        subject = f'NEW CONTACT FORM ENTRY'
        body = f"""
                    A user contacted you through the contact form on your website.
                    Find the details below:
                    Name: { user_name }
                    Email: { user_email} 
                    Subject: { user_subject }
                    Message: { user_message }

                """
        senders_mail = settings.EMAIL_HOST_USER
        to_address = ['admin@nickelwaves.com']

        email = EmailMessage(subject, body, senders_mail, to_address)

        try:
            email.send()
            # pass
        except: 
            print("Server error")
            pass

        messages.success(request, 'Contact details submitted successfully. We will get back to you shortly.')
        return HttpResponseRedirect(reverse('client:contact'))          

    else:
        return render(request, template_name, {
        'current_year': current_year
        })



def career(request):
    template_name = 'client/career.html'

    images = Image.objects.all()
    videos = Video.objects.all()
    banners = Image.objects.filter(banner=True)
    current_year = datetime.now().year

    if videos.count() > 0:
        video = videos.first()
    else:
        video = None  

    return render(request, template_name, {
        'images': images,
        'videos': videos,
        'banners': banners,
        'video': video,
        'current_year': current_year
    })



def documentation(request):
    template_name = 'client/documentation.html'

    return render(request, template_name, {
        
    })      

client/templates/client/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Nickelwaves | Creative Waves, Endless Possibilites</title>
<meta name="author" content="Themezinho">
<meta name="description" content="Agency & Freelancer Portfolio HTML Template">
<meta name="keywords" content="wave, creatve, portfolio, html, template, carousel, theme, agency, html5">

<!-- SOCIAL MEDIA META -->
<meta property="og:description" content="Nickelwaves | Creative Waves, Endless Possibilites">
<meta property="og:image" content="http://www.acrocapoeira.com/wave/preview.png">
<meta property="og:site_name" content="WAVE">
<meta property="og:title" content="WAVE">
<meta property="og:type" content="website">
<meta property="og:url" content="http://www.acrocapoeira.com/wave">

<!-- TWITTER META -->
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@WAVE">
<meta name="twitter:creator" content="@WAVE">
<meta name="twitter:title" content="WAVE">
<meta name="twitter:description" content="Nickelwaves | Creative Waves, Endless Possibilites">
<meta name="twitter:image" content="http://www.acrocapoeira.com/wave/preview.png">

<!-- FAVICON FILES -->
<link href="{% static 'client/ico/apple-touch-icon-144-precomposed.png' %}" rel="apple-touch-icon-precomposed" sizes="144x144">
<link href="{% static 'client/ico/apple-touch-icon-114-precomposed.png' %}" rel="apple-touch-icon-precomposed" sizes="114x114">
<link href="{% static 'client/ico/apple-touch-icon-72-precomposed.png' %}" rel="apple-touch-icon-precomposed" sizes="72x72">
<link href="{% static 'client/ico/apple-touch-icon-57-precomposed.png' %}" rel="apple-touch-icon-precomposed">
<link href="{% static 'client/images/favicon.png' %}" rel="shortcut icon">

<!-- CSS FILES -->
<link rel="stylesheet" href="{% static 'client/css/main.css' %}" media="all">

</head>
<body>
<div class="loading">
  <div class="loader">
    <h2 class="loading-text cd-headline clip is-full-width"> <span class="cd-words-wrapper"> <b class="is-visible">Hey please wait</b> <b>Still loading</b></span> </h2>
    <div class="loading-image"><img src="{% static 'client/images/loading.gif' %}" alt="Image"></div>
  </div>
  <!-- end loader --> 
</div>
<!-- end loading -->
<div class="transition-overlay"></div>
<!-- end transition-overlay -->
<div class="navigation" role="navigation">

  <!-- end video-bg -->
  <div class="table">
    <div class="inner">
      <nav>
        <ul>
          <li><a href="{% url 'client:index' %}">HOME</a></li>
          <li><a href="{% url 'client:wave' %}" class="transition">ABOUT US</a></li>
          <li><a href="{% url 'client:showcase' %}">OUR WORKS</a></li>
          <li><a href="{% url 'client:services' %}" class="transition">SERVICES</a></li>
          <li><a href="{% url 'client:news' %}" class="transition">BLOG</a></li>
          <li><a href="{% url 'client:contact' %}" class="transition">CONTACT</a></li>
          {% comment %} <li><a href="{% url 'login:login' %}" class="transition">LOGIN</a></li> {% endcomment %}
        </ul>
      </nav>
      <span class="copyright">© {{ current_year }} Nickelwaves | Creative Waves, Endless Possibilites</span> </div>
    <!-- end inner --> 
  </div>
  <!-- end table --> 
</div>
<!-- end navigation -->
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="row">
      <div class="col-xs-12"> 
        <a href="{% url 'client:index' %}"><img src="{% static 'client/images/logo.png' %}" alt="Image" class="logo"></a>
        <div class="hamburger-menu"> <span></span> <span></span> <span></span> <span></span> </div>
      </div>
      <!-- end col-12 --> 
    </div>
    <!-- end row --> 
  </div>
  <!-- end container --> 
</nav>
<!-- end navbar -->




{% block content %}

{% endblock %}



<div class="footer-space"></div>
<footer>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 text-center"> <img src="{% static 'client/images/logo.png' %}" alt="Image" class="logo">
        <h3>Creative Waves, Endless Possibilites</h3>
      </div>
      <!-- end col-12 -->
      <div class="col-xs-12">
        <div class="sub-footer"> <span class="copyright">© {{ current_year }} Nickelwaves | Creative Waves, Endless Possibilites</span>
          <ul>
            <li> <a href="{% url 'client:contact' %}">Contact Us</a></li>
            <li> <a href="{% url 'client:news' %}">Blog</a></li>
            <li> <a href="https://web.facebook.com/profile.php?id=100075774083134" target="_blank">Facebook</a></li>
            <li> <a href="https://www.instagram.com/nickelwaves?igsh=NjE0ZTQ4YzN5cWdw" target="_blank">Instagram</a></li>
          </ul>
        </div>
        <!-- end sub-footer --> 
      </div>
      <!-- end col-12 --> 
    </div>
    <!-- end row --> 
  </div>
  <!-- end container --> 
</footer>
<!-- end footer --> 


<!-- JS FILES --> 
<script src=" {% static 'client/js/jquery.min.js' %}"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>
  {% if messages %}
  {% for msg in messages %}
    swal('{{ msg }}');

  {% endfor %}

{% endif %}
</script>
<script type="text/javascript">
(function($) {
	$(window).load(function(){
		$(".loading .loading-image").addClass("dissappear");
		$(".loading .loading-text").addClass("dissappear");
		$(".slider").addClass("goes-up");
		$(".navbar-default").addClass("show");
		$('.loading').delay(1000).addClass("fade-out");	
	});
})(jQuery)
</script> 

{% block script %}

{% endblock script %}
{% comment %} <script src="https://code.jquery.com/jquery-3.5.1.js"></script> {% endcomment %}

<script src="{% static 'client/js/bootstrap.min.js' %}"></script> 
<script src="{% static 'client/js/waypoints.min.js' %}"></script> 
<script src="{% static 'client/js/jquery.counterup.min.js' %}"></script> 
<script src="{% static 'client/js/jquery.textrotater.js' %}"></script> 
<script src="{% static 'client/js/jquery.stellar.js' %}"></script> 
<script src="{% static 'client/js/jquery.vopacity.js' %}"></script> 
<script src="{% static 'client/js/wow.js' %}"></script> 
<script src="{% static 'client/js/masonry.min.js' %}"></script> 
<script src="{% static 'client/js/jquery.swipebox.js' %}"></script> 
<script src="{% static 'client/js/jquery.themepunch.tools.min.js' %}" type='text/javascript' ></script> 
<script src="{% static 'client/js/jquery.themepunch.revolution.min.js' %}" type='text/javascript' ></script> 
<script src="{% static 'client/js/settings.js' %}" type='text/javascript' ></script> 
<script src="{% static 'client/js/scripts.js' %}" type="text/javascript"></script>

</body>
</html>

client/templates/client/career.html
{% extends 'client/base.html' %}
{% load static %}
{% block content %}


<section class="int-header hero6">
  <div class="table">
    <div class="inner">
      <div class="container">
        <h3>wave cAreer</h3>
        <p>We are always looking for people with a creative vision</p>
        <img src="{% static 'client/images/icon-mouse.png' %}" alt="Image"> </div>
      <!-- end container --> 
    </div>
    <!-- end inner --> 
  </div>
  <!-- end table --> 
</section>
<!-- end int-header -->
<main>
  <section class="career">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="title-box">
            <h2 class="wow fadeInUp" data-wow-delay="0.05s">.career</h2>
            <h5 class="wow fadeInUp" data-wow-delay="0.10s">We are always looking for peoples with a creative vision.</h5>
            <span class="shape wow fadeInUp" data-wow-delay="0.15s">O</span> </div>
          <!-- end title-box --> 
        </div>
        <!-- end col-12 -->
        <div class="col-md-4">
          <h4>Digital Art Director</h4>
          <p>If you are in love with concept, ideas, campaigns, story telling & responsive awesomeness for the digital age send us your portfolio.</p>
          <a href="#">APPLY NOW</a> </div>
        <!-- end col-4 -->
        <div class="col-md-4">
          <h4>Front-END Developer</h4>
          <p>We are looking for a mastermind that turns consumer insights into solid digital strategies connecting brands with people.</p>
          <a href="#">APPLY NOW</a> </div>
        <!-- end col-4 -->
        <div class="col-md-4">
          <h4>Digital Strategist</h4>
          <p>If you are able to make sense of research data, find a clear way in a complex world and turn it into digital propositions, work your magic with us.</p>
          <a href="#">APPLY NOW</a> </div>
        <!-- end col-4 --> 
        <div class="col-xs-12">
        	<form class="resume-form">
            	<h3>SEND YOUR RESUME</h3>
            	<div class="form-group">
                	<label>Your name</label>
                    <input type="text">
                </div>
                <!-- end form-group -->
            	<div class="form-group">
                	<label>Your e-mail</label>
                    <input type="text">
                </div>
                <!-- end form-group -->
            	<div class="form-group">
                	<label>Your Resume (DOCX - PDF)</label>
                    <input type="file">
                </div>
                <!-- end form-group --><div class="form-group">
                	<label>Your message</label>
                    <textarea></textarea>
                </div>
                <!-- end form-group -->
                <div class="form-group">
                	<button type="submit">APPLY NOW</button>
                </div>
                <!-- end form-group -->
            </form>
        </div>
        <!-- end col-12 -->
      </div>
      <!-- end row --> 
    </div>
    <!-- end container --> 
  </section>
  <!-- end news --> 
</main>



{% endblock %}

client/templates/client/contact.html
{% extends 'client/base.html' %}
{% load static %}
{% block content %}


<section class="int-header hero5">
  <div class="table">
    <div class="inner">
      <div class="container">
        
      <!-- end container --> 
    </div>
    <!-- end inner --> 
  </div>
  <!-- end table --> 
</section>
<!-- end int-header -->
<main>
  <section class="contact-info">
    <div class="container">
      <div class="row">
        <div class="col-md-4 wow fadeInUp" data-wow-delay="0.05s">
          <h3>CONTACT INFOS</h3>
          <p>Drop by for a coffee or leave us a message the unique services provided to your customers. Creativity for us something personal</p>
        </div>
        <!-- end col-4 -->
        <div class="col-md-8 wow fadeInUp" data-wow-delay="0.10s">
          <div class="row">
            <div class="col-md-4 col-sm-4 text-right">
              <h4>ADDRESS</h4>
              <span>Haatso, Ecomog, Street<br>
                Residence Makarios, House No. GE273</span> </div>
            <!-- end col-4 -->
            <div class="col-md-4 col-sm-4 text-right">
              <h4>PHONES</h4>
              <span>+233 24 722 3238</span> </div>
            <!-- end col-4 -->
            <div class="col-md-4 col-sm-4 text-right">
              <h4>E-MAIL</h4>
              <span><a href="mailto:admin@nickelwaves.com">admin@nickelwaves.com</a></span> </div>
            <!-- end col-4 --> 
          </div>
          <!-- end row --> 
        </div>
        <!-- end col-8 --> 
      </div>
      <!-- end row --> 
    </div>
    <!-- end container --> 
  </section>
  <!-- end contact-info -->

  

  <!-- end mao -->
  <section class="contact-form">
    <div class="container">
      <div class="row">
      <div class="col-xs-12">
          <div class="title-box">
            <h2 class="wow fadeInUp" data-wow-delay="0.05s">.say hello</h2>
            <h5 class="wow fadeInUp" data-wow-delay="0.10s">How can we help or assist you. We have a passion for building </h5>
            <span class="shape wow fadeInUp" data-wow-delay="0.15s">O</span> </div>
          <!-- end title-box --> 
        </div>
        <!-- end col-12 -->
        <div class="col-xs-12 wow fadeInUp" data-wow-delay="0.15s">
          <form id="contact" name="contact" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label>Your name</label>
               <input type="text" name="name" id="name" required>
            </div>
            <!-- end form-group -->
            <div class="form-group">
              <label>Your e-mail</label>
               <input type="text" name="email" id="email" required>
            </div>
            <!-- end form-group -->
            <div class="form-group">
              <label>Subject</label>
              <input type="text" name="subject" id="subject" required>
            </div>
            <!-- end form-group -->
            <div class="form-group">
              <textarea name="message" id="message" required></textarea>
            </div>
            <!-- end form-group -->
            <div class="form-group">
              <button id="submit" type="submit" name="submit">SEND NOW</button>
            </div>
            <!-- end form-group -->
          </form>
          <div id="success" class="alert alert-success" role="alert">
          <p>Your message was sent successfully! We will be in touch as soon as we can.</p>
        </div>
        <!-- end success -->
        <div id="error" class="alert alert-danger" role="alert">
          <p>Something went wrong, try refreshing and submitting the form again.</p>
        </div>
        <!-- end error -->
        </div>
        <!-- end col-12 --> 
      </div>
      <!-- end row --> 
    </div>
    <!-- end container --> 
  </section>
  <!-- end contact-form  --> 
</main>

{% endblock %}

client/templates/client/news-detail.html
{% extends 'client/base.html' %}
{% load static %}

{% block content %}




<section class="gallerybanner hero6" style="background-image: url('{{ blog.blog_file.url }}')">
  
	<div class="gallerybanner__content">
		<div class="gallerybanner_title container">       
      <h3>{{ blog.heading }}</h3>
      <p>{{ blog.subheading }}</p>
      <img src="{% static 'client/images/icon-mouse.png' %}" alt="Image"> </div>
	</div>
</section>


<main>
  <section class="news">
  	<div class="container">
    	<div class="row">
        	<div class="col-xs-12">
            	<div class="news-post">
                	{% comment %} <figure><img src="{{ blog.blog_file.url }}" alt="Image"></figure> {% endcomment %}
                    <figcaption>
                      <small class="text-uppercase mb-5" style="margin-bottom: 10%;">Posted On: {{ blog.date_created|date:'jS F, Y' }}</small><br><br><br>
                    	{% comment %} <h3>{{ blog.heading }}</h3>
                        <p>{{ blog.subheading }}</p>
                        <blockquote>
                        </blockquote> {% endcomment %}
                        <p>{{ blog.body }}</p>
                    </figcaption>
                </div>
                <!-- end news-post -->
            </div>
            <!-- end col-12 -->
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
  </section>
  <!-- end news -->
</main>


{% endblock %}

client/templates/client/news.html
{% extends 'client/base.html' %}
{% load static %}
{% block content %}



{% comment %} <section class="int-header hero4">
  <div class="table">
    <div class="inner">
      <div class="container">
        <h3>wave news</h3>
        <p>Drop by for a coffee or leave us a message using contact form</p>
        <img src="{% static 'client/images/icon-mouse.png' %}" alt="Image"> </div>
      <!-- end container --> 
    </div>
    <!-- end inner --> 
  </div>
  <!-- end table --> 
</section>
<!-- end int-header --> {% endcomment %}

<section class="gallerybanner hero4">
	<div class="gallerybanner__content">
		<div class="gallerybanner_title container">       
      <h3>Our Blog</h3>
      <p>Our ambition is to build the world’s strongest brands.</p>
      <img src="{% static 'client/images/icon-mouse.png' %}" alt="Image"> </div>
	</div>
</section>


<main>
  <section class="news">
  	<div class="container">
    	<div class="row">

        	<div class="col-xs-12">

           {% for blog in blogs %}
           <div class="news-post">
               <figure><img src="{{ blog.blog_file.url }}" alt="Image"></figure>
                 <figcaption>
                 <small class="text-uppercase">{{ blog.date_created|date:'jS F, Y' }}</small>
                   <h3><a href="{% url 'client:news_detail' id=blog.id %}">{{ blog.heading }}</a></h3>
                     <p>{{ blog.subheading }}</p>
                 </figcaption>
             </div>
         {% endfor %}   
            </div>
            <!-- end col-12 -->
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
  </section>
  <!-- end news -->
</main>


{% endblock %}

 

client/templates/client/showcase.html
{% extends 'client/base.html' %}
{% load static %}
{% block content %}


<section class="gallerybanner hero1">
	<div class="gallerybanner__content">
		<div class="gallerybanner_title container">       
      <h3>Our Works</h3>
      <p>Our ambition is to build the world’s strongest brands. Brands that disrupt the status quo and are leaders in what they do.</p>
      <img src="{% static 'client/images/icon-mouse.png' %}" alt="Image"> </div>
	</div>
</section>

<main>
  <section class="showcase">
    <div class="header">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <h2 class="wow fadeInUp" data-wow-delay="0.5s">.our works</h2>
            <h5 class="wow fadeInUp" data-wow-delay="0.10s">Amazing features with creative portfolio</h5>
            <span class="shape wow fadeInUp" data-wow-delay="0.15s">O</span> </div>
          <!-- end col-12 --> 
        </div>
        <!-- end row --> 
      </div>
      <!-- end container --> 
    </div>
    <!-- end header -->


   <div class="portfolio" style="margin-bottom:20%;">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <ul class="portfolio-masonry">
              
              {% for image in images %}
              <li class="wow fadeInUp" data-wow-delay="0.05s">
                <figure><img src="{{ image.image_file.url }}" alt="{{ image.image_name }}">
                 <a href="{{ image.image_file.url }}" data-rel="gallery" class="swipebox text-uppercase" title="{{ image.image_name }}"> 
                 <figcaption class="bg-color4">
                    <div class="table">
                      <div class="inner text-uppercase"> <span>O</span> {{ image.image_name }} </div>
                    </div>
                  </figcaption>
                  </a>
                </figure>
              </li>
              {% endfor %}
              
            </ul>
          </div>
          <!-- end col-12 --> 
        </div>
        <!-- end row --> 
      </div>
      <!-- end container --> 
    </div>
    <!-- end portfolio --> 
  </section>
  <!-- end showcase --> 
</main>


{% endblock %}

client/templates/client/work-detail.html
{% extends 'client/base.html' %}
{% load static %}
{% block content %}


<section class="int-header" style="background:url(images/project-detail-hero.jpg) center; background-size:cover;">
  <div class="table">
    <div class="inner">
      <div class="container">
        <h3>vegae e cAm</h3>
        <p>Agency that brings ambitious brands to the next level by transforming their digital business.</p>
        <img src="{% static 'client/images/icon-mouse.png' %}" alt="Image"> </div>
      <!-- end container --> 
    </div>
    <!-- end inner --> 
  </div>
  <!-- end table --> 
</section>
<!-- end int-header -->
<main>
  <section class="project-detail">
    <div class="container">
      <div class="row">
        <div class="col-md-5 wow fadeInUp" data-wow-delay="0.05s">
          <h4>TECHNOLOGY</h4>
          <p>HTML 5, CSS, CSS Transition, jQuery, Php, MySQL</p>
        </div>
        <!-- end col-5 -->
        <div class="col-md-3 wow fadeInUp" data-wow-delay="0.10s">
          <h4>URL</h4>
          <p>www.yahoo.com </p>
          
        </div>
        <!-- end col-3 -->
        <div class="col-md-4 wow fadeInUp" data-wow-delay="0.15s">
          <h4>CLIENTS</h4>
          <p>E-Cam digital oculus company ltd.</p>
        </div>
        <!-- end col-4 --> 
        <div class="col-xs-12 spacing wow fadeInUp">
        <h4>DESCRIPTION</h4>
        <p>The goal of design was to provide direction for the new wearable device. Emotion is designed to take advantage of the EEG technology will develop further in the future. It is able to detect the moment while listening to music touched, and record the environment emotion of the moment received. The saved video recordings can be shared with others.</p>
        </div>
      <!-- end col-12 -->
        <div class="col-xs-12 spacing wow fadeInUp">
      	<img src="{% static 'client/images/mockup-macbook.png' %}" alt="Image" class="full-width">
      </div>
      <!-- end col-12 -->
      <div class="col-xs-12 text-center spacing wow fadeInUp">
      	<img src="{% static 'client/images/mockup-iphone.png' %}" alt="Image">
      </div>
      <!-- end col-12 -->
      </div>
      <!-- end row -->
    </div>
    <!--end container -->
  </section>
  <!-- end project-detail -->
</main>

{% endblock %}