login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.login, name="login"),

    path('forgot-password/', views.forgotPassword, name="forgotPassword"),
    path('verify-code/', views.verifyCode, name="verifyCode"),

    path('reset-password/<str:token>', views.resetPassword, name='resetPassword'),

    # path('index/', views.index, name="index"),
]

superuser/urls.py
from django.urls import path
from . import views

app_name = 'superuser'

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    
    # Images
    path('images/', views.viewImages, name="viewImages"),
    path('add-image/', views.addImage, name="addImage"),
    path('edit-image/<int:id>/', views.editImage, name='editImage'),
    path('delete-image/<int:id>', views.deleteImage, name='deleteImage'),

    # Blogs
    path('blogs/', views.viewBlogs, name="viewBlogs"),
    path('add-blog/', views.addBlog, name="addBlog"),
    path('edit-blog/<int:id>/', views.editBlog, name='editBlog'),
    path('view-blog/<int:id>/', views.viewBlog, name='viewBlog'),
    path('delete-blog/<int:id>', views.deleteBlog, name='deleteBlog'),

    # Videos
    path('videos/', views.viewVideos, name="viewVideos"),
    path('add-video/', views.addVideo, name="addVideo"),
    path('edit-video/<int:id>/', views.editVideo, name='editVideo'),
    path('delete-video/<int:id>', views.deleteVideo, name='deleteVideo'),


    path('profile/', views.profile, name="profile"),
    
    path('reset-password/', views.resetPassword, name="resetPassword"),

    path('logout/', views.user_logout, name='user_logout'),

]

wavex/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt
from wavex import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superuser/', include('superuser.urls')),
    path('login/', include('login.urls')),
    path('', include('client.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

superuser/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    is_admin = models.BooleanField(default=True)
    
    def __str__(self):
        return self.username


class Image(models.Model):
    image_file = models.ImageField(upload_to='image-uploads/', default='', null=True)
    image_name = models.CharField(max_length=100, null=True, default="")
    heading = models.CharField(max_length=100, null=True, default="")
    subheading = models.CharField(max_length=100, null=True, default="")
    banner = models.BooleanField(default=False)
    date_uploaded = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.image_name



class Blog(models.Model):
    blog_file = models.ImageField(upload_to='blog-uploads/', default='', null=True)
    heading = models.CharField(max_length=100, null=True, default="")
    subheading = models.CharField(max_length=100, null=True, default="")
    body = models.CharField(max_length=500, null=True, default="")
    date_created= models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.heading


class Video(models.Model):
    video_file = models.CharField(max_length=5000, null=True, default="")
    video_name = models.CharField(max_length=100, null=True, default="")
    banner = models.BooleanField(default=False)
    date_uploaded = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.video_name


class Verifications(models.Model):
    email = models.EmailField(max_length=254)
    token = models.CharField(max_length=50)
    verified = models.BooleanField(default=False)
    

    def __str__(self):
        return self.email


class Contact(models.Model):
    name = models.CharField(max_length=100, null=True, default="")
    email = models.EmailField(max_length=254)
    message = models.CharField(max_length=500, null=True, default="")
    date_sent = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

superuser/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib import messages
from django.shortcuts import redirect, render
from .models import *
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_exempt
import requests
import datetime
import json
import random
import string
import os
import environ



# Create your views here.
@login_required(login_url='login:login')
def dashboard(request):
    template_name = 'superuser/dashboard.html'
    page = "Admin Dashboard"

    total_images = Image.objects.all().count()
    total_blogs = Blog.objects.all().count()

    return render(request, template_name, {
        'page': page,
        'total_blogs': total_blogs,
        'total_images': total_images
    })


@login_required(login_url='login:login')
def viewImages(request):
    template_name = 'superuser/view-images.html'
    page = "View Images"

    images = Image.objects.all()

    return render(request, template_name, {
        'page': page,
        'images': images
    }) 


@login_required(login_url='login:login')
def addImage(request):
    template_name = 'superuser/add-image.html'
    page = "Add Image"
    
    if request.method == 'POST':

        banner = True if request.POST.get('banner') else False
        image_name = request.POST.get('image_name')
        heading = request.POST.get('heading')
        subheading = request.POST.get('subheading')

        try:
            image_file = request.FILES.get('image_file')
        except:
            image_file = None 


        try:
            image = Image.objects.create(image_name=image_name, image_file=image_file, banner=banner, heading=heading, subheading=subheading)
            image.save()
            messages.success(request, 'Image added successfully')
            return HttpResponseRedirect(reverse('superuser:viewImages'))  
        except:
            messages.success(request, 'File size too large')
            return HttpResponseRedirect(reverse('superuser:addImage'))  


    else:
        return render(request, template_name, {
            'page': page,
        })


@login_required(login_url='login:login')
def editImage(request, id, **kwargs):
    template_name = 'superuser/edit-image.html'
    page = "Edit Image"

    image = Image.objects.get(id=id)
    
    if request.method == 'POST':
        new_image = request.FILES.get('image_file', None)
        if new_image is not None:
            
            image.image_file = request.FILES.get('image_file', None)

        image.image_name = request.POST.get('image_name')
        image.heading = request.POST.get('heading')
        image.subheading = request.POST.get('subheading')
        image.banner = True if request.POST.get('banner') else image.banner 

        try:
            image.save()

            messages.success(request, 'Image details updated successfully!')
            return redirect('superuser:viewImages')
        
        except:
            messages.success(request, 'File size too large')
            return HttpResponseRedirect(reverse('superuser:editImage', kwargs={'id': id}))

           
    
    else:
        return render(request, template_name, {
            'image': image,
            'page': page,
        }) 


@login_required(login_url='login:login')
def deleteImage(request, id, *args, **kwargs):
     
    if request.method == "POST":
        image = Image.objects.get(id=id)
        image.delete()

    messages.success(request, 'Image deleted successfully!')
    return redirect('superuser:viewImages')




@login_required(login_url='login:login')
def viewBlogs(request):
    template_name = 'superuser/view-blogs.html'
    page = "View Blogs"

    blogs = Blog.objects.all()

    return render(request, template_name, {
        'page': page,
        'blogs': blogs
    }) 


@login_required(login_url='login:login')
def addBlog(request):
    template_name = 'superuser/add-blog.html'
    page = "Add Blog"
    
    if request.method == 'POST':
        heading = request.POST.get('heading')
        subheading = request.POST.get('subheading')
        body = request.POST.get('body')

        try:
            blog_file = request.FILES.get('blog_file')
        except:
            blog_file = None 


        try:
            blog = Blog.objects.create(blog_file=blog_file, heading=heading, subheading=subheading, body=body)
            blog.save()
            messages.success(request, 'Blog added successfully')
            return HttpResponseRedirect(reverse('superuser:viewBlogs'))  
        except:
            messages.success(request, 'File size too large')
            return HttpResponseRedirect(reverse('superuser:viewBlogs'))  


    else:
        return render(request, template_name, {
            'page': page,
        })


@login_required(login_url='login:login')
def editBlog(request, id, **kwargs):
    template_name = 'superuser/edit-blog.html'
    page = "Edit Blog"

    blog = Blog.objects.get(id=id)
    
    if request.method == 'POST':
        new_image = request.FILES.get('blog_file', None)

        if new_image is not None:
            blog.blog_file = request.FILES.get('blog_file', None)

        blog.heading = request.POST.get('heading')
        blog.subheading = request.POST.get('subheading')
        blog.body = request.POST.get('body')

        try:
            blog.save()

            messages.success(request, 'Blog details updated successfully!')
            return redirect('superuser:viewBlogs')
        
        except:
            messages.success(request, 'File size too large')
            return HttpResponseRedirect(reverse('superuser:editBlog', id)) 

    else:
        return render(request, template_name, {
            'blog': blog,
            'page': page,
        }) 


@login_required(login_url='login:login')
def deleteBlog(request, id, *args, **kwargs):
     
    if request.method == "POST":
        blog = Blog.objects.get(id=id)
        blog.delete()

    messages.success(request, 'Blog deleted successfully!')
    return redirect('superuser:viewBlogs')


@login_required(login_url='login:login')
def viewBlog(request, id, *args, **kwargs):
    template_name = 'superuser/view-blog.html'
    page = "View Blog"

    blog = Blog.objects.get(id=id)

    return render(request, template_name, {
        'page': page,
        'blog': blog
    }) 




@login_required(login_url='login:login')
def viewVideos(request):
    template_name = 'superuser/view-videos.html'
    page = "View Videos"

    videos = Video.objects.all()

    return render(request, template_name, {
        'page': page,
        'videos': videos
    }) 


@login_required(login_url='login:login')
def addVideo(request):
    template_name = 'superuser/add-video.html'
    page = "Add Video"
    
    if request.method == 'POST':
        body = json.loads(request.body)
        banner = True if body['banner'] else False
        video_name = body['video_name']
        video_file = body['video_file']


        if video_file:
            video = Video.objects.create(video_name=video_name, video_file=video_file, banner=banner)
            video.save()
        else:
            pass    

        messages.success(request, 'Video added successfully')
        return HttpResponseRedirect(reverse('superuser:viewVideos'))      

    else:
        return render(request, template_name, {
            'page': page,
        })


@login_required(login_url='login:login')
def editVideo(request, id, **kwargs):
    template_name = 'superuser/edit-video.html'
    page = "Edit Video"

    video = Video.objects.get(id=id)

    if request.method == 'POST':
        body = json.loads(request.body)
        video.banner = True if body['banner'] else False
        video.video_name = body['video_name']
        video.video_file = body['video_file']
        video.save()

        messages.success(request, 'Video details updated successfully!')
        return redirect('superuser:viewVideos') 
    
    else:
        return render(request, template_name, {
            'video': video,
            'page': page,
            'id': id
        }) 


@login_required(login_url='login:login')
def deleteVideo(request, id, *args, **kwargs):
     
    if request.method == "POST":
        video = Video.objects.get(id=id)
        video.delete()

    messages.success(request, 'Video deleted successfully!')
    return redirect('superuser:viewVideos')




@login_required(login_url='login:login')
def profile(request):
    template_name = 'superuser/profile.html'
    page = "View Profile"

    return render(request, template_name, {
        'page': page
    }) 

@login_required(login_url='login:login')
def editProfile(request, id, **kwargs):
    template_name = 'superuser/edit-profile.html'
    page = "Edit Profile"

    return render(request, template_name, {
        'page': page
    }) 





@login_required(login_url='login:login')
def resetPassword(request):
    template_name = 'superuser/reset-password.html'
    page = 'Reset Password'
    user=request.user


    if request.method == 'POST':
        password = request.POST.get('password')

        password = make_password(password)
        admin = User.objects.get(id=user.id)

        admin.password = password
        admin.save()

        messages.success(request, 'Password reset successfully!')
        return redirect('superuser:dashboard')

    else:
        return render(request, template_name, {
            'page': page
        })




superuser/templates/superuser/base.html
<!DOCTYPE html>
<html lang="en">
<head>

{% load static %}

<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link href="{% static 'client/ico/apple-touch-icon-144-precomposed.png' %}" rel="apple-touch-icon-precomposed" sizes="144x144">
<link href="{% static 'client/ico/apple-touch-icon-114-precomposed.png' %}" rel="apple-touch-icon-precomposed" sizes="114x114">
<link href="{% static 'client/ico/apple-touch-icon-72-precomposed.png' %}" rel="apple-touch-icon-precomposed" sizes="72x72">
<link href="{% static 'client/ico/apple-touch-icon-57-precomposed.png' %}" rel="apple-touch-icon-precomposed">
<link href="{% static 'client/images/favicon.png' %}" rel="shortcut icon">

<script src="https://cdn.tiny.cloud/1/9kcc64gryhj5x89mbpy1ibpf2a3to5frie13c6zxzqa9w92d/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>

<title>Nickelwaves | {{ page }}</title>

<!--     Fonts and icons     -->
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />

<!-- Nucleo Icons -->
<link href="{% static 'superuser/assets/css/nucleo-icons.css' %}" rel="stylesheet" />
<link href="{% static 'superuser/assets/css/nucleo-svg.css' %}" rel="stylesheet" />
<link href="{% static 'superuser/css/style.css' %}" rel="stylesheet" />


<!-- Font Awesome Icons -->
<script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>

<!-- Material Icons -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">

<!-- CSS Files -->

<link id="pagestyle" href="{% static 'superuser/assets/css/material-dashboard.css?v=3.1.0' %}" rel="stylesheet" />

<script defer data-site="YOUR_DOMAIN_HERE" src="https://api.nepcha.com/js/nepcha-analytics.js"></script>

{% block import %}

{% endblock %}


<style>
  {% block style %}

  {% endblock %}
</style>


  </head>


  <body class="g-sidenav-show bg-gray-100">
    

 <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3  bg-gradient-dark" id="sidenav-main">

  <div class="sidenav-header">
    <a class="navbar-brand m-0" href="{% url 'superuser:dashboard' %}">
      <img src="{% static 'client/images/logo.png' %}" class="navbar-brand-img h-100 ml-5 logo" style="margin-left:20%;" width="50%" height="100%" alt="main_logo">
    </a>
  </div>


  <hr class="horizontal light mt-0 mb-2">

  <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
    <ul class="navbar-nav">
      

        <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'superuser:dashboard' %}">
                
                <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                    <i class="material-icons opacity-10">dashboard</i>
                </div>
                
                <span class="nav-link-text ms-1">Dashboard</span>
            </a>
        </li>

        
        <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'superuser:viewImages' %}">
                
                <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                    <i class="material-icons opacity-10">image</i>
                </div>
                
                <span class="nav-link-text ms-1">Images</span>
            </a>
        </li>

        
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'superuser:viewBlogs' %}">
              
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                  <i class="material-icons opacity-10">book</i>
              </div>
              
              <span class="nav-link-text ms-1">Blogs</span>
          </a>
      </li>

        

        
        <li class="nav-item">
            <a class="nav-link text-white " href="{% url 'superuser:profile' %}">
                
                <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                    <i class="material-icons opacity-10">person</i>
                </div>
                
                <span class="nav-link-text ms-1">Profile</span>
            </a>
        </li>

        <li class="nav-item">
          <a class="nav-link text-white " href="{% url 'superuser:resetPassword' %}">
              
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                  <i class="material-icons opacity-10">lock_person</i>
              </div>
              
              <span class="nav-link-text ms-1">Reset Password</span>
          </a>
      </li>

        
        <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'superuser:user_logout' %}">
                
                <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                    <i class="material-icons opacity-10">logout</i>
                </div>
                
                <span class="nav-link-text ms-1">Logout</span>
            </a>
        </li>

      
    </ul>
  </div>
  
 
  
</aside>


{% block content %}

{% endblock %}



    

        
    {% comment %} <footer class="footer main-content py-4">
      <div class="container-fluid">
        <div class="row align-items-center justify-content-lg-between">
          <div class="col-lg-6 mb-lg-0 mb-4">
            <div class="copyright text-center text-sm text-muted text-lg-start">
              © <script>
                document.write(new Date().getFullYear())
              </script>,
              made with <i class="fa fa-heart"></i> by
              <a href="https://www.creative-tim.com" class="font-weight-bold" target="_blank">Creative Tim</a>
              for a better web.
            </div>
          </div>
          <div class="col-lg-6">
            <ul class="nav nav-footer justify-content-center justify-content-lg-end">
              <li class="nav-item">
                <a href="https://www.creative-tim.com" class="nav-link text-muted" target="_blank">Creative Tim</a>
              </li>
              <li class="nav-item">
                <a href="https://www.creative-tim.com/presentation" class="nav-link text-muted" target="_blank">About Us</a>
              </li>
              <li class="nav-item">
                <a href="https://www.creative-tim.com/blog" class="nav-link text-muted" target="_blank">Blog</a>
              </li>
              <li class="nav-item">
                <a href="https://www.creative-tim.com/license" class="nav-link pe-0 text-muted" target="_blank">License</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
  </footer> {% endcomment %}



<!--   Core JS Files   -->
<script src="{% static 'superuser/js/script.js' %}"></script>

<script src="{% static 'superuser/assets/js/core/popper.min.js' %}" ></script>
<script src="{% static 'superuser/assets/js/core/bootstrap.min.js' %}" ></script>
<script src="{% static 'superuser/assets/js/plugins/perfect-scrollbar.min.js' %}" ></script>
<script src="{% static 'superuser/assets/js/plugins/smooth-scrollbar.min.js' %}" ></script>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script>
  {% if messages %}
  {% for msg in messages %}
    swal('{{ msg }}');

  {% endfor %}

{% endif %}
</script>

{% block script %}

{% endblock %}

<script>
  var win = navigator.platform.indexOf('Win') > -1;
  if (win && document.querySelector('#sidenav-scrollbar')) {
    var options = {
      damping: '0.5'
    }
    Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
  }

  


      const deleteButtons = document.querySelectorAll('.item-delete');
  
      deleteButtons.forEach(button => {
          button.addEventListener('click', function (e) {
              e.preventDefault();
  
              const id = this.getAttribute("id");
              const csrf = document.querySelector('input[name=csrfmiddlewaretoken]').value;
  
              if (confirm("Are you sure you want to delete this item?")) {
                  fetch(this.getAttribute("href"), {
                      method: "POST",
                      headers: {
                          "Content-Type": "application/json",
                          "X-CSRFToken": csrf
                      },
                      body: JSON.stringify({
                          id,
                          csrfmiddlewaretoken: csrf
                      })
                  })
                  .then(response => {
                      
                      return response;
                  })
                  .then(resp => {
                      const divElement = document.getElementById(id);

                      
                      divElement.style.transition = 'background-color 0.5s ease-out, opacity 0.5s ease-out'; // You can adjust duration and timing function as needed

                      divElement.style.backgroundColor = '#ccc';
                      divElement.style.opacity = '0'; 

                      setTimeout(() => {
                        divElement.style.display = 'none';
                      }, 500);
                  })
                  .catch(error => {
                      console.error('Error:', error);
                      // Handle non-JSON response or other errors here
                  });
              }
  
              return false;
          });
      });

  

</script>

<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>


<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{% static 'superuser/assets/js/material-dashboard.min.js?v=3.1.0' %}"></script>
  </body>

</html>

superuser/templates/superuser/edit-profile.html
{% extends 'superuser/base.html' %}
{% load static %}
{% block content %}



<main class="main-content border-radius-lg">

    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" data-scroll="true">
      <div class="container-fluid py-1 px-3 bg-white rounded mt-3">
        <nav aria-label="breadcrumb">
          <h2 class="font-weight-bolder mb-0">Profile</h2>
        </nav>


        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">

            <ul class="navbar-nav  justify-content-end">
              <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
                <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
                  <div class="sidenav-toggler-inner">
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                  </div>
                </a>
              </li>
            </ul>
          </div>

      </div>
    </nav>

    <!-- End Navbar -->

</main>


{% endblock %}

superuser/templates/superuser/profile.html
{% extends 'superuser/base.html' %}
{% load static %}
{% block content %}



<main class="main-content border-radius-lg">

    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" data-scroll="true">
      <div class="container-fluid py-1 px-3 bg-white rounded mt-3">
        <nav aria-label="breadcrumb">
          <h2 class="font-weight-bolder mb-0">Profile</h2>
        </nav>


        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">

            <ul class="navbar-nav  justify-content-end">
              <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
                <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
                  <div class="sidenav-toggler-inner">
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                  </div>
                </a>
              </li>
            </ul>
          </div>

      </div>
    </nav>

    <!-- End Navbar -->

</main>


{% endblock %}

superuser/templates/superuser/view-blogs.html
{% extends 'superuser/base.html' %}
{% load static %}
{% block style %}
 
{% endblock %}

{% block content %}


<main class="main-content border-radius-lg">

    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" data-scroll="true">
      <div class="container-fluid py-1 px-3 bg-white rounded mt-3">
        <nav aria-label="breadcrumb">
          <h2 class="font-weight-bolder mb-0">Blogs</h2>
        </nav>

        <div class="float mt-3">
            <a href="{% url 'superuser:addBlog' %}"><button class="btn btn-primary rounded-lg">Add Blog<i class="material-icons" style="font-size: 1.5em;">add_circle</i></button></a>
        </div>
        

        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">

            <ul class="navbar-nav  justify-content-end">
              <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
                <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
                  <div class="sidenav-toggler-inner">
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                  </div>
                </a>
              </li>
            </ul>
          </div>

      </div>
    </nav>

    <!-- End Navbar -->


    <div class="container-fluid bg-white rounded  p-4 m-4">
        <div class="container-md sm-p-10 md-p-8">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
                {% csrf_token %}
                <!-- CARD 1 -->
                {% for blog in blogs %}
                <div class="col" id="{{ blog.id }}">
                    <div class="rounded overflow-hidden shadow bg-white">
                    <a href="#"></a>

                    <div class="position-relative">
                        <img class="img-fluid object-cover" src="{{ blog.blog_file.url }}" alt="placeholder">
                    </div>

                    <div class="px-3 py-2 mb-auto">
                       <a href="{% url 'superuser:viewBlog' id=blog.id %}">
                        <p class="text-lg fw-bold text-dark transition-500 inline-block mb-2">{{ blog.heading }}</p>
                       </a>
                    </div>

                    <div class="border-bottom border-dark mx-3"></div>

                    <div class="px-3 py-2 d-flex flex-row justify-content-between bg-white">

                        <span class="py-1 mb-3 text-sm mt-0 d-flex align-items-center">
                            <i class="material-icons" style="font-size: 1.5em;">table_view</i>
                            <span class="ms-1 text-sm font-light">{{ blog.date_created|date:'jS F, Y' }}</span>
                        </span>

                        <span class="py-1 text-sm d-flex align-items-center">
                            <a href="{% url 'superuser:editBlog' id=blog.id %}" class="m-1"><button class="btn btn-sm btn-danger rounded-2"><i class="material-icons" style="font-size: 1.5em;">edit</i></button></a>
                            <a href="{% url 'superuser:deleteBlog' id=blog.id %}" class="item-delete" id="{{ blog.id }}"><button class="btn btn-sm btn-primary rounded-2"><i class="material-icons" style="font-size: 1.5em;">delete</i></button></a>
                        </span>
        
                    </div>

                    </div>
                </div>
                {% endfor %}

    
            </div>
    
        </div>
    </div>
            


</main>
 


{% endblock %}